=== Consensys/linea-token-list/json/schema/l2-token-list-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/eea-oasis/l2/schemas/CanonicalTokenList.json",
  "$comment": "{\"term\": \"CanonicalTokenList\", \"@id\": \"https://github.com/eea-oasis/l2#CanonicalTokenList\"}",
  "title": "CanonicalTokenList",
  "description": "Canonical Token List",
  "type": "object",
  "required": [
    "type",
    "tokenListId",
    "name",
    "createdAt",
    "updatedAt",
    "versions",
    "tokens"
  ],
  "properties": {
    "@context": {
      "type": "array"
    },
    "type": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array"
        }
      ],
      "examples": ["CanonicalTokenList"]
    },
    "tokenListId": {
      "$comment": "{\"term\": \"tokenListId\", \"@id\": \"https://schema.org/identifier\"}",
      "title": "tokenListId",
      "description": "A resolvable URI to the publicly accessible place where this list can be found following the RFC 3986 standard.",
      "type": "string",
      "examples": [
        "https://ipfs.io/ipns/k51qzi5uqu5dkkciu33khkzbcmxtyhn376i1e83tya8kuy7z9euedzyr5nhoew"
      ]
    },
    "name": {
      "$comment": "{\"term\": \"name\", \"@id\": \"https://schema.org/name\"}",
      "title": "name",
      "description": "Token List name",
      "type": "string",
      "examples": ["Aggregate Canonical Token List"]
    },
    "logoURI": {
      "$comment": "{\"term\": \"logoURI\", \"@id\": \"https://schema.org/identifier\"}",
      "title": "logoURI",
      "description": "URI or URL of the token list logo following the RFC 3986 standard",
      "type": "string",
      "examples": [
        "https://ipfs.io/ipns/k51qzi5uqu5dh5kbbff1ucw3ksphpy3vxx4en4dbtfh90pvw4mzd8nfm5r5fnl"
      ]
    },
    "keywords": {
      "$comment": "{\"term\": \"keywords\", \"@id\": \"https://schema.org/DefinedTerm\"}",
      "title": "keywords",
      "description": "List of key words for the token list",
      "type": "array",
      "examples": ["Aggregate Token List"]
    },
    "createdAt": {
      "$comment": "{\"term\": \"createdAt\", \"@id\": \"https://schema.org/datePublished\"}",
      "title": "createdAt",
      "description": "Date and time token list was created",
      "type": "string",
      "examples": ["2022-05-08"]
    },
    "updatedAt": {
      "$comment": "{\"term\": \"updatedAt\", \"@id\": \"https://schema.org/dateModified\"}",
      "title": "updatedAt",
      "description": "Date and time token list was updated",
      "type": "string",
      "examples": ["2022-05-09"]
    },
    "versions": {
      "$comment": "{\"term\": \"versions\", \"@id\": \"https://schema.org/version\"}",
      "title": "versions",
      "description": "Versions of the canonical token list",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["major", "minor", "patch"],
        "properties": {
          "major": {
            "$comment": "{\"term\": \"major\", \"@id\": \"https://schema.org/Number\"}",
            "title": "major",
            "description": "Major Version Number of the Token List",
            "type": "integer",
            "examples": [1]
          },
          "minor": {
            "$comment": "{\"term\": \"minor\", \"@id\": \"https://schema.org/Number\"}",
            "title": "minor",
            "description": "Minor Version Number of the Token List",
            "type": "integer",
            "examples": [1]
          },
          "patch": {
            "$comment": "{\"term\": \"patch\", \"@id\": \"https://schema.org/Number\"}",
            "title": "patch",
            "description": "Patch Number of the Token List",
            "type": "integer",
            "examples": [1]
          }
        }
      }
    },
    "tokens": {
      "title": "Listed Token Entry",
      "description": "Listed Token Entry",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "chainId",
          "chainURI",
          "tokenId",
          "tokenType",
          "address",
          "name",
          "symbol",
          "decimals",
          "createdAt",
          "updatedAt"
        ],
        "properties": {
          "chainId": {
            "$comment": "{\"term\": \"chainId\", \"@id\": \"https://schema.org/identifier\"}",
            "title": "chainId",
            "description": "The typically used number identifier for the chain on which the token was issued.",
            "type": "number",
            "examples": [137]
          },
          "chainURI": {
            "$comment": "{\"term\": \"chainURI\", \"@id\": \"https://schema.org/identifier\"}",
            "title": "chainURI",
            "description": "A resolvable URI to the genesis block of the chain on which the token was issued following the RFC 3986 standard.",
            "type": "string",
            "examples": ["https://polygonscan.com/block/0"]
          },
          "genesisBlockHash": {
            "$comment": "{\"term\": \"genesisBlockHash\", \"@id\": \"https://schema.org/sha256\"}",
            "title": "genesisBlockHash",
            "description": "The hash of the genesis block of the chain on which the token was issued.",
            "type": "string",
            "examples": [
              "0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b"
            ]
          },
          "tokenIssuerId": {
            "$comment": "{\"term\": \"tokenIssuerId\", \"@id\": \"https://schema.org/identifier\"}",
            "title": "tokenIssuerId",
            "description": "A resolvable URI identifying the token issuer following the RFC 3986 standard.",
            "type": "string",
            "examples": [
              "https://polygonscan.com/address/0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b"
            ]
          },
          "tokenIssuerName": {
            "$comment": "{\"term\": \"tokenIssuerName\", \"@id\": \"https://schema.org/name\"}",
            "title": "tokenIssuerName",
            "description": "The name oof the token issuer.",
            "type": "string",
            "examples": ["Matic"]
          },
          "tokenId": {
            "$comment": "{\"term\": \"tokenId\", \"@id\": \"https://schema.org/identifier\"}",
            "title": "tokenId",
            "description": "A resolvable URI of the token following the RFC 3986 standard to for example the deployment transaction of the token, or a DID identifying the token and its issuer.",
            "type": "string",
            "example": [
              "https://polygonscan.com/address/0x0000000000000000000000000000000000001010"
            ]
          },
          "tokenType": {
            "$comment": "{\"term\": \"tokenType\", \"@id\": \"https://schema.org/StructuredValue\"}",
            "title": "tokenType",
            "description": "Describes the type of token.",
            "type": "array",
            "examples": [["fungible", "transferable"]]
          },
          "tokenDesc": {
            "$comment": "{\"term\": \"tokenDesc\", \"@id\": \"https://schema.org/description\"}",
            "title": "tokenDesc",
            "description": "Brief description of the token and its functionality.",
            "type": "string",
            "examples": ["Protocol Token for the Matic Network"]
          },
          "standard": {
            "$comment": "{\"term\": \"standard\", \"@id\": \"https://schema.org/citation\"}",
            "title": "standard",
            "description": "A resolvable URI to the description of the token standard.",
            "type": "string",
            "examples": [
              "https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md"
            ]
          },
          "address": {
            "$comment": "{\"term\": \"address\", \"@id\": \"https://schema.org/identifier\"}",
            "title": "address",
            "description": "Address of the token smart contract.",
            "type": "string",
            "examples": ["0x0000000000000000000000000000000000001010"]
          },
          "addressType": {
            "$comment": "{\"term\": \"address\", \"@id\": \"https://schema.org/Intangible\"}",
            "title": "addressType",
            "description": "AddressType of the token smart contract.",
            "type": "string",
            "examples": ["MaticNameSpace"]
          },
          "addressAlg": {
            "$comment": "{\"term\": \"addressAlg\", \"@id\": \"https://schema.org/algorithm\"}",
            "title": "addressAlg",
            "description": "Algorithm used to create the address e.g. CREATE2 or the standard ethereum address construction which is the last 40 characters/20 bytes of the Keccak-256 hash of a secp256k1 public key.",
            "type": "string",
            "examples": ["CREATE2"]
          },
          "name": {
            "$comment": "{\"term\": \"name\", \"@id\": \"https://schema.org/name\"}",
            "title": "name",
            "description": "Token name.",
            "type": "string",
            "examples": ["Matic"]
          },
          "symbol": {
            "$comment": "{\"term\": \"symbol\", \"@id\": \"https://schema.org/currency\"}",
            "title": "symbol",
            "description": "Token symbol e.g. ETH.",
            "type": "string",
            "examples": ["MATIC"]
          },
          "humanReadableTokenSymbol": {
            "$comment": "{\"term\": \"humanReadableTokenSymbol\", \"@id\": \"https://schema.org/currency\"}",
            "title": "humanReadableTokenSymbol",
            "description": "A Token symbol e.g. ETH, concatenated with the `chainId` the token was issued on or bridged to, e.g. ETH-1",
            "type": "string",
            "examples": ["MATIC-137"]
          },
          "decimals": {
            "$comment": "{\"term\": \"decimals\", \"@id\": \"https://schema.org/Number\"}",
            "title": "decimals",
            "description": "Allowed number of decimals for the listed token. This property may be named differently by token standards e.g. granularity for ERC-777",
            "type": "integer",
            "examples": [18]
          },
          "logoURI": {
            "$comment": "{\"term\": \"logoURI\", \"@id\": \"https://schema.org/identifier\"}",
            "title": "logoURI",
            "description": "URI or URL of the token logo following the RFC 3986 standard.",
            "type": "string",
            "examples": ["https://polygonscan.com/token/images/matic_32.png"]
          },
          "createdAt": {
            "$comment": "{\"term\": \"createdAt\", \"@id\": \"https://schema.org/datePublished\"}",
            "title": "createdAt",
            "description": "Date and time token was created",
            "type": "string",
            "examples": ["2020-05-31"]
          },
          "updatedAt": {
            "$comment": "{\"term\": \"updatedAt\", \"@id\": \"https://schema.org/dateModified\"}",
            "title": "updatedAt",
            "description": "Date and time token was updated",
            "type": "string",
            "examples": ["2020-05-31"]
          },
          "extensions": {
            "title": "extensions",
            "description": "Extension to the token list entry to specify an origin chain if the token entry refers to another chain other than the origin chain of the token",
            "type": "array",
            "items": {
              "type": "object",
              "required": ["rootChainId", "rootChainURI", "rootAddress"],
              "properties": {
                "rootChainId": {
                  "$comment": "{\"term\": \"rootChainId\", \"@id\": \"https://schema.org/identifier\"}",
                  "title": "rootChainId",
                  "description": "The typically used number identifier for the root chain on which the token was originally issued.",
                  "type": "number",
                  "examples": [137]
                },
                "rootChainURI": {
                  "$comment": "{\"term\": \"rootChainURI\", \"@id\": \"https://schema.org/identifier\"}",
                  "title": "rootChainURI",
                  "description": "A resolvable URI to the genesis block of the root chain on which the token was originally issued following the RFC 3986 standard.",
                  "type": "string",
                  "examples": ["https://polygonscan.com/block/0"]
                },
                "rootAddress": {
                  "$comment": "{\"term\": \"rootAddress\", \"@id\": \"https://schema.org/identifier\"}",
                  "title": "rootAddress",
                  "description": "Root address of the token smart contract.",
                  "type": "string",
                  "examples": ["0x0000000000000000000000000000000000001010"]
                }
              }
            }
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== Consensys/linea-token-list/json/linea-sepolia-token-shortlist.json
{
  "type": "LineaTokenList",
  "tokenListId": "https://raw.githubusercontent.com/Consensys/linea-token-list/main/json/linea-sepolia-token-shortlist.json",
  "name": "Linea Sepolia Token List",
  "createdAt": "2024-03-29",
  "updatedAt": "2024-04-26",
  "versions": [
    {
      "major": 1,
      "minor": 2,
      "patch": 0
    }
  ],
  "tokens": [
    {
      "chainId": 59141,
      "chainURI": "https://sepolia.lineascan.build/block/0",
      "tokenId": "https://sepolia.lineascan.build/address/0xf17a935A89cB4CBc176cd5afeBCB9805e5Ed7c1A",
      "tokenType": ["bridge-reserved", "external-bridge"],
      "address": "0xf17a935A89cB4CBc176cd5afeBCB9805e5Ed7c1A",
      "name": "USDC",
      "symbol": "USDC",
      "decimals": 6,
      "createdAt": "2024-03-27",
      "updatedAt": "2024-03-27",
      "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
      "extension": {
        "rootChainId": 11155111,
        "rootChainURI": "https://sepolia.etherscan.io/block/0",
        "rootAddress": "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
      }
    },
    {
      "chainId": 59141,
      "chainURI": "https://sepolia.lineascan.build/block/0",
      "tokenId": "https://sepolia.lineascan.build/address/0x06565ed324Ee9fb4DB0FF80B7eDbE4Cb007555a3",
      "tokenType": ["native"],
      "address": "0x06565ed324Ee9fb4DB0FF80B7eDbE4Cb007555a3",
      "name": "Wrapped Ether",
      "symbol": "WETH",
      "decimals": 18,
      "createdAt": "2024-03-29",
      "updatedAt": "2024-03-29",
      "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/2396.png"
    },
    {
      "chainId": 59141,
      "chainURI": "https://sepolia.lineascan.build/block/0",
      "tokenId": "https://sepolia.lineascan.build/address/0xFcAE759E3f149721f674Ea720361a76bBe67Ea8c",
      "tokenType": ["native"],
      "address": "0xFcAE759E3f149721f674Ea720361a76bBe67Ea8c",
      "name": "Dunachain",
      "symbol": "DUNA",
      "decimals": 18,
      "createdAt": "2024-09-26",
      "updatedAt": "2024-09-27",
      "logoURI": "https://i.ibb.co/VCpK4bR/1.png" 
    }
  ]
}

=== Consensys/linea-token-list/json/linea-goerli-token-list.json
{
  "type": "CanonicalTokenList",
  "tokenListId": "https://ipfs.io/ipns/k51qzi5uqu5dkkciu33khkzbcmxtyhn376i1e83tya8kuy7z9euedzyr5nhoew",
  "name": "Aggregate Canonical Token List",
  "createdAt": "2022-05-08",
  "updatedAt": "2022-05-09",
  "versions": [
    {
      "major": 1,
      "minor": 1,
      "patch": 1
    }
  ],
  "tokens": [
    {
      "chainId": 137,
      "chainURI": "https://polygonscan.com/block/0",
      "tokenId": "https://polygonscan.com/address/0x0000000000000000000000000000000000001010",
      "tokenType": ["fungible", "transferable"],
      "address": "0x0000000000000000000000000000000000001010",
      "name": "Matic",
      "symbol": "MATIC",
      "decimals": 18,
      "createdAt": "2020-05-31",
      "updatedAt": "2020-05-31",
      "logoURI": "https://polygonscan.com/token/images/matic_32.png",
      "extensions": [
        {
          "rootChainId": 137,
          "rootChainURI": "https://polygonscan.com/block/0",
          "rootAddress": "0x0000000000000000000000000000000000001010"
        }
      ]
    },
    {
      "chainId": 59140,
      "chainURI": "https://goerli.lineascan.build/block/0",
      "tokenId": "https://goerli.lineascan.build/token/0x7823e8dcc8bfc23ea3ac899eb86921f90e80f499",
      "tokenType": [
        "bridged"
      ],
      "address": "0x7823e8dcc8bfc23ea3ac899eb86921f90e80f499",
      "name": "Uniswap",
      "symbol": "UNI",
      "decimals": 18,
      "createdAt": "2023-06-23",
      "updatedAt": "2023-06-23",
      "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png",
      "extension": {
        "rootChainId": 5,
        "rootChainURI": "https://goerli.etherscan.io/block/0",
        "rootAddress": "0x41E5E6045f91B61AACC99edca0967D518fB44CFB"
      }
    }
  ]
}

=== Consensys/linea-token-list/json/linea-goerli-token-shortlist.json
{
  "type": "LineaTokenList",
  "tokenListId": "TBD",
  "name": "Linea Goerli Token List",
  "createdAt": "2023-06-23",
  "updatedAt": "2023-06-23",
  "versions": [
    {
      "major": 1,
      "minor": 1,
      "patch": 1
    }
  ],
  "tokens": [
    {
      "chainId": 59140,
      "chainURI": "https://goerli.lineascan.build/block/0",
      "tokenId": "https://goerli.lineascan.build/token/0x7823e8dcc8bfc23ea3ac899eb86921f90e80f499",
      "tokenType": ["bridged"],
      "address": "0x7823e8dcc8bfc23ea3ac899eb86921f90e80f499",
      "name": "Uniswap",
      "symbol": "UNI",
      "decimals": 18,
      "createdAt": "2023-06-26",
      "updatedAt": "2023-06-26",
      "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png",
      "extension": {
        "rootChainId": 5,
        "rootChainURI": "https://goerli.etherscan.io/block/0",
        "rootAddress": "0x41E5E6045f91B61AACC99edca0967D518fB44CFB"
      }
    },
    {
      "chainId": 59140,
      "chainURI": "https://goerli.lineascan.build/block/0",
      "tokenId": "https://goerli.lineascan.build/token/0x2C1b868d6596a18e32E61B901E4060C872647b6C",
      "tokenType": ["native"],
      "address": "0x2C1b868d6596a18e32E61B901E4060C872647b6C",
      "name": "Wrapped Ethereum",
      "symbol": "WETH",
      "decimals": 18,
      "createdAt": "2023-06-26",
      "updatedAt": "2023-06-26",
      "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/2396.png"
    }
  ]
}

=== Consensys/linea-token-list/json/json/linea-sepolia-token-shortlist.json
{
  "type": "LineaTokenList",
  "tokenListId": "https://raw.githubusercontent.com/Consensys/linea-token-list/main/json/linea-sepolia-token-shortlist.json",
  "name": "Linea Sepolia Token List",
  "createdAt": "2024-03-29",
  "updatedAt": "2024-03-29",
  "versions": [
    {
      "major": 1,
      "minor": 0,
      "patch": 0
    }
  ],
  "tokens": []
}
